### ISSUE TITLE
Prestashop versión 1.7.7 (o superior)- Módulo no aparece en pedidos

### ISSUE THREAD

**Issue by Visolo** [cecabank/cecabank-prestashop#2]
En versiones superiores a 1.7.7 el módulo no se muestra en el detalle de los pedidos y no se puede hacer un reembolso desde prestashop.

Según la documentación de prestashop los nombres de los hooks han cambiado en esta versión.

Además, no permite desenganchar el módulo de los hooks erróneos.

**Comment by rodriciru** [comment]
necesitamos que esto funcione en las versiones 1.7.7, que es la actual!!
